---
# Repository configuration for wetransform managed repositories

# Reference presets that should apply to this repository
presets:
  - allow-merge-commit # allow merge commit in addition to rebase in PRs
